### ISSUE TITLE
Hardy: Pomodoro

### ISSUE THREAD

**Issue by Permas-Teo** [AY1920S2-CS2103T-W16-1/main#17]
* Hardy: Pomodoro
    * v1.2: Basic Pomodoro runs and stops at 25/5 minutes intervals
    * v1.3: User can stop Pomodoro halfway to mark tasks as done, pause Pomodoro timer to be continued at the next call to Pomodoro

**Comment by BransonNg** [comment]
For v1.3
* When editing a Pomodoro task, should update the task in the Pomodoro display
* When deleting a Pomodoro task, should either pre-empt the user that the task is running or cancel the Pomodoro if user decides to delete such a task
