### ISSUE TITLE
Pass pomodoro data to statistics

### ISSUE THREAD

**Issue by artlee06** [AY1920S2-CS2103T-W16-1/main#96]

**Comment by Permas-Teo** [comment]
CS2103T Individual Assignment for Sir Hardoh

**Problem statement:** We want to keep track of data in the past n (7) days while accounting for usage across different days. (eg. Use 1 day, never touch for 2 days, or 10 days, and use again)

**Tentative solution:** statistics.json will store and track the DayData (Date [LocalDate], PomDurationData [Integer], TasksDoneData [Integer]) for the past n days. Note that you construct Date, PomDurationData and TasksDoneData using Strings.

Statistics will create a list of empty DayData objects for the past 7 days (including current day) upon initialisation in statistics.json. I have defined several helper methods in Statistics for your usage. 
```
fetch() // reinitialises dayDataList to current day while retaining stored data.
updatesDayData(DayData dayData) // Auto-checks and replaces a new DayData object at the same Date
getDayDataFromDate(Date date) // Gets DayData object at current date.

```

**Proposed Implementation:**

Check if current date exist in list using getDayDataFromDate.

LEVEL 1
If date exist, simply add data to the DayData obtained.
Then update the list using updatesDayData.

LEVEL 2
If date doesn't exist, this means list is outdated, and should be reinitialised using fetch to update list to the new day, which also deletes the outdated days in the list.
Repeat LEVEL 1 for new day.
If this is the event where day crosses to the next day, remember to repeat LEVEL 1 for the previous day too.
 
Please feel free to propose/make any changes to this implementation.
